---
- name: Remove existing Ghostty config folder
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/ghostty"
    state: absent
  become: false

- name: Symlink ghostty
  become: false
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/dotfiles/.config/ghostty"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/ghostty"
    state: link
    force: yes

