---
- name: Remove existing neovim config folder
  become: false
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/nvim"
    state: absent

- name: Link neovim config
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/dotfiles/.config/nvim"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/nvim"
    state: link
    force: yes
