---
- name: Ensure Zsh is installed (Arch Linux)
  become: true
  community.general.pacman:
    name: zsh
    state: present
  when: ansible_facts['os_family'] == "Archlinux"

- name: Ensure Zsh is installed (macOS)
  community.general.homebrew:
    name: zsh
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: Install Zoxide (Arch Linux)
  become: true
  community.general.pacman:
    name: zoxide
    state: present
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install Zoxide (macOS)
  community.general.homebrew:
    name: zoxide
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: Change default shell to zsh (Arch Linux)
  become: true
  ansible.builtin.user:
    name: "{{ ansible_facts['user_id'] }}"
    shell: /usr/bin/zsh
  when: ansible_facts['os_family'] == "Archlinux"

# Cleanup: Remove old Oh My Zsh installation (run with --tags cleanup)
- name: Remove old Oh My Zsh installation
  become: false
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.oh-my-zsh"
    state: absent
  tags: [never, cleanup]
