---
- name: Install Ghostty (Arch)
  become: true
  community.general.pacman:
    name: ghostty
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install Ghostty (macOS)
  community.general.homebrew:
    name: ghostty
    state: present
  when: ansible_facts['os_family'] == "Darwin"