---
- name: Install tmux (Arch Linux)
  become: true
  community.general.pacman:
    name: tmux
    state: present
  when: ansible_facts['os_family'] == "Archlinux"

- name: Install tmux (macOS)
  community.general.homebrew:
    name: tmux
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: Remove existing tmux config folder
  ansible.builtin.file:
    path: "{{ ansible_facts['env']['HOME'] }}/.config/tmux"
    state: absent
  become: false

- name: Symlink tmux
  become: false
  ansible.builtin.file:
    src: "{{ ansible_facts['env']['HOME'] }}/dotfiles/.config/tmux"
    dest: "{{ ansible_facts['env']['HOME'] }}/.config/tmux"
    state: link
    force: yes
