---
- name: Install starship (macOS)
  community.general.homebrew:
    name: starship
    state: present
  when: ansible_facts['os_family'] == "Darwin"

- name: Install starship (Arch Linux)
  community.general.pacman:
    name: starship
    state: present
  become: true
  when: ansible_facts['os_family'] == "Archlinux"
